/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.112
 * Generated at: 2025-11-20 04:56:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.campussync.model.Course;

public final class manage_005fcourses_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("com.campussync.model.Course");
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    javax.servlet.http.HttpSession s = request.getSession(false);

    if (s == null || !"admin".equals(s.getAttribute("role"))) {
        response.sendRedirect(request.getContextPath() + "/login.jsp");
        return;
    }

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Manage Courses - CampusSync</title>\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        * { margin: 0; padding: 0; box-sizing: border-box; }\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("            background: #f7fafc;\r\n");
      out.write("            color: #2d3748;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .header {\r\n");
      out.write("            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 20px 30px;\r\n");
      out.write("            box-shadow: 0 2px 8px rgba(0,0,0,0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .header a {\r\n");
      out.write("            color: rgba(255,255,255,0.9);\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            display: inline-flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .back-arrow { margin-right: 6px; }\r\n");
      out.write("\r\n");
      out.write("        .container {\r\n");
      out.write("            max-width: 900px;\r\n");
      out.write("            margin: 30px auto;\r\n");
      out.write("            padding: 0 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-section, .table-section {\r\n");
      out.write("            background: white;\r\n");
      out.write("            padding: 30px;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            box-shadow: 0 2px 8px rgba(0,0,0,0.08);\r\n");
      out.write("            margin-bottom: 40px;\r\n");
      out.write("            border: 1px solid #e2e8f0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        h3 { margin-bottom: 18px; font-size: 20px; font-weight: 700; }\r\n");
      out.write("\r\n");
      out.write("        .form-group { margin-bottom: 18px; }\r\n");
      out.write("        label { font-size: 14px; font-weight: 600; display: block; margin-bottom: 6px; }\r\n");
      out.write("\r\n");
      out.write("        input[type=\"text\"] {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            max-width: 300px;\r\n");
      out.write("            padding: 10px 14px;\r\n");
      out.write("            border: 2px solid #e2e8f0;\r\n");
      out.write("            border-radius: 6px;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            transition: .3s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        input:focus {\r\n");
      out.write("            border-color: #667eea;\r\n");
      out.write("            box-shadow: 0 0 0 3px rgba(102,126,234,.15);\r\n");
      out.write("            outline: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        button {\r\n");
      out.write("            padding: 10px 24px;\r\n");
      out.write("            background: linear-gradient(135deg,#667eea 0%,#764ba2 100%);\r\n");
      out.write("            border: none;\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            border-radius: 6px;\r\n");
      out.write("            transition: .3s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        button:hover { transform: translateY(-3px); box-shadow: 0 8px 16px rgba(102,126,234,.35); }\r\n");
      out.write("\r\n");
      out.write("        table { width: 100%; border-collapse: collapse; font-size: 14px; }\r\n");
      out.write("        th { background: #f7fafc; padding: 14px; font-weight: 600; border-bottom: 2px solid #e2e8f0; text-align: left; }\r\n");
      out.write("        td { padding: 14px; border-bottom: 1px solid #e2e8f0; color: #4a5568; }\r\n");
      out.write("        tr:hover { background: #f7fafc; }\r\n");
      out.write("\r\n");
      out.write("        .actions a { color: #667eea; font-weight: 600; margin-right: 12px; text-decoration: none; }\r\n");
      out.write("        .actions a.delete { color: #e53e3e; }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("    <h2>Manage Courses</h2>\r\n");
      out.write("    <a href=\"");
      out.print( request.getContextPath() );
      out.write("/adminPanel\">\r\n");
      out.write("        <svg class=\"back-arrow\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"\r\n");
      out.write("             style=\"width: 18px; height: 18px;\">\r\n");
      out.write("            <polyline points=\"15 18 9 12 15 6\"></polyline>\r\n");
      out.write("        </svg>\r\n");
      out.write("        Back to Dashboard\r\n");
      out.write("    </a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Add Course Form -->\r\n");
      out.write("    <div class=\"form-section\">\r\n");
      out.write("        <h3>Add New Course</h3>\r\n");
      out.write("\r\n");
      out.write("        <form action=\"");
      out.print( request.getContextPath() );
      out.write("/CourseServlet\" method=\"post\">\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label>Course Name</label>\r\n");
      out.write("                <input type=\"text\" name=\"course_name\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <button type=\"submit\">Add Course</button>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Course List -->\r\n");
      out.write("    <div class=\"table-section\">\r\n");
      out.write("        <h3>Course List</h3>\r\n");
      out.write("\r\n");
      out.write("        <table>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th>ID</th>\r\n");
      out.write("                <th>Course</th>\r\n");
      out.write("                <th>Actions</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("\r\n");
      out.write("            ");

                List<Course> courses = (List<Course>) request.getAttribute("courseData");

                if (courses != null && !courses.isEmpty()) {
                    for (Course c : courses) {
            
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>");
      out.print( c.getCourseId() );
      out.write("</td>\r\n");
      out.write("                <td>");
      out.print( c.getCourseName() );
      out.write("</td>\r\n");
      out.write("                <td class=\"actions\">\r\n");
      out.write("                    <a href=\"");
      out.print( request.getContextPath() );
      out.write("/adminPanel?action=editCourse&id=");
      out.print( c.getCourseId() );
      out.write("\">Edit</a>\r\n");
      out.write("                    <a href=\"");
      out.print( request.getContextPath() );
      out.write("/adminPanel?action=deleteCourse&id=");
      out.print( c.getCourseId() );
      out.write("\" class=\"delete\">Delete</a>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            ");

                    }
                } else {
            
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td colspan=\"3\" style=\"text-align:center; padding:20px;\">No courses available</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </table>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
