/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.112
 * Generated at: 2025-11-19 11:20:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.ResultSet;

public final class manage_005fstudents_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("java.sql.ResultSet");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    javax.servlet.http.HttpSession s = request.getSession(false);
    if (s == null || !"admin".equals(s.getAttribute("role"))) {
        response.sendRedirect(request.getContextPath() + "/login.jsp");
        return;
    }

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>Manage Students - CampusSync</title>\n");
      out.write("\n");
      out.write("    <style>\n");
      out.write("        * {\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("            box-sizing: border-box;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        body {\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n");
      out.write("            background: #f7fafc;\n");
      out.write("            color: #2d3748;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Added modern header styling */\n");
      out.write("        .header {\n");
      out.write("            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\n");
      out.write("            color: white;\n");
      out.write("            padding: 20px 30px;\n");
      out.write("            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);\n");
      out.write("            animation: slideDown 0.4s ease-out;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @keyframes slideDown {\n");
      out.write("            from {\n");
      out.write("                opacity: 0;\n");
      out.write("                transform: translateY(-20px);\n");
      out.write("            }\n");
      out.write("            to {\n");
      out.write("                opacity: 1;\n");
      out.write("                transform: translateY(0);\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .back-arrow {\n");
      out.write("            display: inline-block;\n");
      out.write("            margin-right: 6px;\n");
      out.write("            animation: slideInLeft 0.4s ease-out;\n");
      out.write("            transition: transform 0.3s;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @keyframes slideInLeft {\n");
      out.write("            from {\n");
      out.write("                opacity: 0;\n");
      out.write("                transform: translateX(-10px);\n");
      out.write("            }\n");
      out.write("            to {\n");
      out.write("                opacity: 1;\n");
      out.write("                transform: translateX(0);\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .header a:hover .back-arrow {\n");
      out.write("            transform: translateX(-3px);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .header a {\n");
      out.write("            color: rgba(255, 255, 255, 0.9);\n");
      out.write("            text-decoration: none;\n");
      out.write("            font-size: 14px;\n");
      out.write("            transition: opacity 0.3s;\n");
      out.write("            display: inline-flex;\n");
      out.write("            align-items: center;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Modernized form styling */\n");
      out.write("        .form-section {\n");
      out.write("            background: white;\n");
      out.write("            padding: 30px;\n");
      out.write("            border-radius: 10px;\n");
      out.write("            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);\n");
      out.write("            margin-bottom: 40px;\n");
      out.write("            border: 1px solid #e2e8f0;\n");
      out.write("            animation: fadeInUp 0.5s ease-out;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @keyframes fadeInUp {\n");
      out.write("            from {\n");
      out.write("                opacity: 0;\n");
      out.write("                transform: translateY(20px);\n");
      out.write("            }\n");
      out.write("            to {\n");
      out.write("                opacity: 1;\n");
      out.write("                transform: translateY(0);\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .table-section {\n");
      out.write("            background: white;\n");
      out.write("            padding: 30px;\n");
      out.write("            border-radius: 10px;\n");
      out.write("            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);\n");
      out.write("            border: 1px solid #e2e8f0;\n");
      out.write("            overflow-x: auto;\n");
      out.write("            animation: fadeInUp 0.5s ease-out 0.1s both;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        table {\n");
      out.write("            width: 100%;\n");
      out.write("            border-collapse: collapse;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        table th {\n");
      out.write("            background: #f7fafc;\n");
      out.write("            padding: 14px;\n");
      out.write("            text-align: left;\n");
      out.write("            font-weight: 600;\n");
      out.write("            color: #2d3748;\n");
      out.write("            border-bottom: 2px solid #e2e8f0;\n");
      out.write("            font-size: 14px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        table td {\n");
      out.write("            padding: 14px;\n");
      out.write("            border-bottom: 1px solid #e2e8f0;\n");
      out.write("            color: #4a5568;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        table tr {\n");
      out.write("            transition: all 0.2s ease-out;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        table tr:hover {\n");
      out.write("            background: #f7fafc;\n");
      out.write("            box-shadow: inset 0 0 10px rgba(102, 126, 234, 0.08);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-group {\n");
      out.write("            margin-bottom: 16px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        label {\n");
      out.write("            display: block;\n");
      out.write("            font-weight: 600;\n");
      out.write("            margin-bottom: 6px;\n");
      out.write("            color: #2d3748;\n");
      out.write("            font-size: 14px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        input[type=\"text\"],\n");
      out.write("        input[type=\"email\"],\n");
      out.write("        input[type=\"password\"],\n");
      out.write("        input[type=\"number\"] {\n");
      out.write("            width: 100%;\n");
      out.write("            max-width: 300px;\n");
      out.write("            padding: 10px 12px;\n");
      out.write("            border: 2px solid #e2e8f0;\n");
      out.write("            border-radius: 6px;\n");
      out.write("            font-size: 14px;\n");
      out.write("            transition: all 0.3s;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        input[type=\"text\"]:focus,\n");
      out.write("        input[type=\"email\"]:focus,\n");
      out.write("        input[type=\"password\"]:focus,\n");
      out.write("        input[type=\"number\"]:focus {\n");
      out.write("            outline: none;\n");
      out.write("            border-color: #667eea;\n");
      out.write("            box-shadow: 0 0 0 3px rgba(102, 126, 234, 0.1);\n");
      out.write("            animation: inputFocus 0.3s ease-out;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @keyframes inputFocus {\n");
      out.write("            from {\n");
      out.write("                box-shadow: 0 0 0 0px rgba(102, 126, 234, 0.2);\n");
      out.write("            }\n");
      out.write("            to {\n");
      out.write("                box-shadow: 0 0 0 3px rgba(102, 126, 234, 0.1);\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        button {\n");
      out.write("            padding: 10px 24px;\n");
      out.write("            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\n");
      out.write("            border: none;\n");
      out.write("            color: white;\n");
      out.write("            font-size: 14px;\n");
      out.write("            font-weight: 600;\n");
      out.write("            cursor: pointer;\n");
      out.write("            border-radius: 6px;\n");
      out.write("            transition: all 0.3s;\n");
      out.write("            margin-top: 10px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        button:hover {\n");
      out.write("            transform: translateY(-3px);\n");
      out.write("            box-shadow: 0 8px 16px rgba(102, 126, 234, 0.35);\n");
      out.write("            animation: buttonShine 0.6s ease-out;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @keyframes buttonShine {\n");
      out.write("            0% {\n");
      out.write("                box-shadow: 0 4px 12px rgba(102, 126, 234, 0.3);\n");
      out.write("            }\n");
      out.write("            50% {\n");
      out.write("                box-shadow: 0 8px 20px rgba(102, 126, 234, 0.5);\n");
      out.write("            }\n");
      out.write("            100% {\n");
      out.write("                box-shadow: 0 8px 16px rgba(102, 126, 234, 0.35);\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<div class=\"header\">\n");
      out.write("    <h2>Manage Students</h2>\n");
      out.write("    <!-- Added SVG back arrow icon -->\n");
      out.write("    <a href=\"");
      out.print( request.getContextPath() );
      out.write("/adminPanel\">\n");
      out.write("        <svg class=\"back-arrow\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" style=\"width: 18px; height: 18px;\">\n");
      out.write("            <polyline points=\"15 18 9 12 15 6\"></polyline>\n");
      out.write("        </svg>\n");
      out.write("        Back to Dashboard\n");
      out.write("    </a>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"container\">\n");
      out.write("    <div class=\"form-section\">\n");
      out.write("        <h3>Add New Student</h3>\n");
      out.write("\n");
      out.write("        <form action=\"");
      out.print( request.getContextPath() );
      out.write("/adminPanel\" method=\"post\">\n");
      out.write("            <input type=\"hidden\" name=\"action\" value=\"addStudent\">\n");
      out.write("\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label for=\"name\">Full Name</label>\n");
      out.write("                <input type=\"text\" id=\"name\" name=\"name\" required>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label for=\"email\">Email Address</label>\n");
      out.write("                <input type=\"email\" id=\"email\" name=\"email\" required>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label for=\"password\">Password</label>\n");
      out.write("                <input type=\"password\" id=\"password\" name=\"password\" required>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label for=\"course\">Course</label>\n");
      out.write("                <input type=\"text\" id=\"course\" name=\"course\" required>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label for=\"semester\">Semester</label>\n");
      out.write("                <input type=\"number\" id=\"semester\" name=\"semester\" min=\"1\" required>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <button type=\"submit\">Add Student</button>\n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"table-section\">\n");
      out.write("        <h3>Student List</h3>\n");
      out.write("\n");
      out.write("        <table border=\"1\" cellpadding=\"5\">\n");
      out.write("            <tr>\n");
      out.write("                <th>ID</th>\n");
      out.write("                <th>Name</th>\n");
      out.write("                <th>Email</th>\n");
      out.write("                <th>Course</th>\n");
      out.write("                <th>Semester</th>\n");
      out.write("            </tr>\n");
      out.write("\n");
      out.write("            ");

                ResultSet rs = (ResultSet) request.getAttribute("students");

                while (rs != null && rs.next()) {
            
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                    <td>");
      out.print( rs.getInt("student_id") );
      out.write("</td>\n");
      out.write("                    <td>");
      out.print( rs.getString("name") );
      out.write("</td>\n");
      out.write("                    <td>");
      out.print( rs.getString("email") );
      out.write("</td>\n");
      out.write("                    <td>");
      out.print( rs.getString("course") );
      out.write("</td>\n");
      out.write("                    <td>");
      out.print( rs.getInt("semester") );
      out.write("</td>\n");
      out.write("                </tr>\n");
      out.write("            ");

                }
            
      out.write("\n");
      out.write("\n");
      out.write("        </table>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
