/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.112
 * Generated at: 2025-12-05 14:13:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Campus Sync - Smart College Management System</title>\n");
      out.write("    \n");
      out.write("    <!-- Added Font Awesome icons library for professional icon support -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\n");
      out.write("\n");
      out.write("    <style>\n");
      out.write("        * {\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("            box-sizing: border-box;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        body {\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n");
      out.write("            background: #ffffff;\n");
      out.write("            min-height: 100vh;\n");
      out.write("            overflow-x: hidden;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Hero Section: Split layout with college campus image on the left and content on the right */\n");
      out.write("        .hero {\n");
      out.write("            display: grid;\n");
      out.write("            grid-template-columns: 1fr 1fr;\n");
      out.write("            align-items: center;\n");
      out.write("            min-height: 100vh;\n");
      out.write("            gap: 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* College Campus Image Section */\n");
      out.write("        .hero__image-container {\n");
      out.write("            position: relative;\n");
      out.write("            width: 100%;\n");
      out.write("            height: 100vh;\n");
      out.write("            overflow: hidden;\n");
      out.write("            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .hero__image {\n");
      out.write("            width: 100%;\n");
      out.write("            height: 100%;\n");
      out.write("            object-fit: cover;\n");
      out.write("            object-position: center;\n");
      out.write("            display: block;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Overlay gradient for better text readability if needed */\n");
      out.write("        .hero__image-overlay {\n");
      out.write("            position: absolute;\n");
      out.write("            top: 0;\n");
      out.write("            left: 0;\n");
      out.write("            width: 100%;\n");
      out.write("            height: 100%;\n");
      out.write("            background: linear-gradient(135deg, rgba(102, 126, 234, 0.15) 0%, rgba(118, 75, 162, 0.15) 100%);\n");
      out.write("            pointer-events: none;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Content Section on the Right */\n");
      out.write("        .hero__content {\n");
      out.write("            padding: 60px 50px;\n");
      out.write("            display: flex;\n");
      out.write("            flex-direction: column;\n");
      out.write("            justify-content: center;\n");
      out.write("            height: 100vh;\n");
      out.write("            background: #ffffff;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .hero__badge {\n");
      out.write("            display: inline-block;\n");
      out.write("            background: rgba(102, 126, 234, 0.1);\n");
      out.write("            color: #667eea;\n");
      out.write("            padding: 8px 16px;\n");
      out.write("            border-radius: 20px;\n");
      out.write("            font-size: 12px;\n");
      out.write("            font-weight: 600;\n");
      out.write("            text-transform: uppercase;\n");
      out.write("            letter-spacing: 0.5px;\n");
      out.write("            margin-bottom: 24px;\n");
      out.write("            width: fit-content;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .hero__title {\n");
      out.write("            font-size: 52px;\n");
      out.write("            font-weight: 800;\n");
      out.write("            color: #1a202c;\n");
      out.write("            line-height: 1.2;\n");
      out.write("            margin-bottom: 20px;\n");
      out.write("            letter-spacing: -0.5px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .hero__description {\n");
      out.write("            font-size: 18px;\n");
      out.write("            color: #718096;\n");
      out.write("            line-height: 1.8;\n");
      out.write("            margin-bottom: 40px;\n");
      out.write("            max-width: 450px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .hero__features {\n");
      out.write("            display: grid;\n");
      out.write("            grid-template-columns: 1fr 1fr;\n");
      out.write("            gap: 24px;\n");
      out.write("            margin-bottom: 40px;\n");
      out.write("            max-width: 450px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Updated feature card styling to work with Font Awesome icons */\n");
      out.write("        .feature {\n");
      out.write("            display: flex;\n");
      out.write("            flex-direction: column;\n");
      out.write("            gap: 12px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* New icon styling for Font Awesome icons */\n");
      out.write("        .feature__icon {\n");
      out.write("            font-size: 32px;\n");
      out.write("            color: #667eea;\n");
      out.write("            width: 40px;\n");
      out.write("            height: 40px;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .feature__title {\n");
      out.write("            font-size: 12px;\n");
      out.write("            font-weight: 700;\n");
      out.write("            color: #718096;\n");
      out.write("            text-transform: uppercase;\n");
      out.write("            letter-spacing: 0.5px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .feature__value {\n");
      out.write("            font-size: 20px;\n");
      out.write("            font-weight: 800;\n");
      out.write("            color: #667eea;\n");
      out.write("            line-height: 1.2;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .hero__cta-group {\n");
      out.write("            display: flex;\n");
      out.write("            gap: 16px;\n");
      out.write("            flex-wrap: wrap;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn {\n");
      out.write("            display: inline-flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            text-decoration: none;\n");
      out.write("            padding: 16px 32px;\n");
      out.write("            border-radius: 12px;\n");
      out.write("            font-size: 15px;\n");
      out.write("            font-weight: 600;\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("            border: 2px solid transparent;\n");
      out.write("            cursor: pointer;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn--primary {\n");
      out.write("            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\n");
      out.write("            color: white;\n");
      out.write("            box-shadow: 0 8px 24px rgba(102, 126, 234, 0.3);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn--primary:hover {\n");
      out.write("            transform: translateY(-3px);\n");
      out.write("            box-shadow: 0 12px 32px rgba(102, 126, 234, 0.4);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn--secondary {\n");
      out.write("            background: white;\n");
      out.write("            color: #667eea;\n");
      out.write("            border: 2px solid #e2e8f0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn--secondary:hover {\n");
      out.write("            border-color: #667eea;\n");
      out.write("            background: rgba(102, 126, 234, 0.05);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Responsive Design */\n");
      out.write("        @media (max-width: 1024px) {\n");
      out.write("            .hero {\n");
      out.write("                grid-template-columns: 1fr;\n");
      out.write("                min-height: auto;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .hero__image-container {\n");
      out.write("                height: 500px;\n");
      out.write("                min-height: 400px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .hero__content {\n");
      out.write("                height: auto;\n");
      out.write("                padding: 50px 40px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .hero__title {\n");
      out.write("                font-size: 42px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .hero__features {\n");
      out.write("                max-width: 100%;\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @media (max-width: 768px) {\n");
      out.write("            .hero__content {\n");
      out.write("                padding: 40px 24px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .hero__title {\n");
      out.write("                font-size: 36px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .hero__description {\n");
      out.write("                font-size: 16px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .hero__features {\n");
      out.write("                grid-template-columns: 1fr;\n");
      out.write("                max-width: 100%;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .hero__cta-group {\n");
      out.write("                flex-direction: column;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .btn {\n");
      out.write("                width: 100%;\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Animation for hero elements */\n");
      out.write("        @keyframes slideInLeft {\n");
      out.write("            from {\n");
      out.write("                opacity: 0;\n");
      out.write("                transform: translateX(-30px);\n");
      out.write("            }\n");
      out.write("            to {\n");
      out.write("                opacity: 1;\n");
      out.write("                transform: translateX(0);\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @keyframes slideInRight {\n");
      out.write("            from {\n");
      out.write("                opacity: 0;\n");
      out.write("                transform: translateX(30px);\n");
      out.write("            }\n");
      out.write("            to {\n");
      out.write("                opacity: 1;\n");
      out.write("                transform: translateX(0);\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .hero__image-container {\n");
      out.write("            animation: slideInLeft 0.7s ease-out;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .hero__content {\n");
      out.write("            animation: slideInRight 0.7s ease-out 0.1s both;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("    <!-- Hero Section with College Campus Image -->\n");
      out.write("    <section class=\"hero\">\n");
      out.write("        <!-- Left: College Campus Image -->\n");
      out.write("        <div class=\"hero__image-container\">\n");
      out.write("            <img \n");
      out.write("                src=\"https://images.pexels.com/photos/159740/library-la-trobe-study-students-159740.jpeg?height=1080&width=1080\"\n");
      out.write("                alt=\"Modern college campus with students\"\n");
      out.write("                class=\"hero__image\"\n");
      out.write("                loading=\"lazy\"\n");
      out.write("            >\n");
      out.write("            <div class=\"hero__image-overlay\"></div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Right: Content Section -->\n");
      out.write("        <div class=\"hero__content\">\n");
      out.write("            <span class=\"hero__badge\">Smart Campus Management</span>\n");
      out.write("            \n");
      out.write("            <h1 class=\"hero__title\">Campus Sync</h1>\n");
      out.write("            \n");
      out.write("            <p class=\"hero__description\">\n");
      out.write("                Streamline college operations with our comprehensive management system. \n");
      out.write("                Connect administrators, faculty, and students on one unified platform.\n");
      out.write("            </p>\n");
      out.write("\n");
      out.write("            <!-- Key Features Grid -->\n");
      out.write("            <!-- Replaced emoji icons with Font Awesome icons for professional appearance -->\n");
      out.write("            <div class=\"hero__features\">\n");
      out.write("                <div class=\"feature\">\n");
      out.write("                    <div class=\"feature__icon\">\n");
      out.write("                        <i class=\"fas fa-chart-line\"></i>\n");
      out.write("                    </div>\n");
      out.write("                    <span class=\"feature__title\">Real-time</span>\n");
      out.write("                    <span class=\"feature__value\">Dashboard</span>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"feature\">\n");
      out.write("                    <div class=\"feature__icon\">\n");
      out.write("                        <i class=\"fas fa-users\"></i>\n");
      out.write("                    </div>\n");
      out.write("                    <span class=\"feature__title\">Multi-user</span>\n");
      out.write("                    <span class=\"feature__value\">Access</span>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"feature\">\n");
      out.write("                    <div class=\"feature__icon\">\n");
      out.write("                        <i class=\"fas fa-clipboard-check\"></i>\n");
      out.write("                    </div>\n");
      out.write("                    <span class=\"feature__title\">Attendance</span>\n");
      out.write("                    <span class=\"feature__value\">Tracking</span>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"feature\">\n");
      out.write("                    <div class=\"feature__icon\">\n");
      out.write("                        <i class=\"fas fa-star\"></i>\n");
      out.write("                    </div>\n");
      out.write("                    <span class=\"feature__title\">Grade</span>\n");
      out.write("                    <span class=\"feature__value\">Management</span>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!-- Call-to-Action Buttons -->\n");
      out.write("            <div class=\"hero__cta-group\">\n");
      out.write("                <a href=\"login.jsp\" class=\"btn btn--primary\">Get Started Now</a>\n");
      out.write("                <a href=\"#features\" class=\"btn btn--secondary\">Learn More</a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
