/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.112
 * Generated at: 2025-12-05 14:13:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>Login - Campus Sync</title>\n");
      out.write("\n");
      out.write("    <style>\n");
      out.write("        * {\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("            box-sizing: border-box;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        body {\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n");
      out.write("            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: center;\n");
      out.write("            align-items: center;\n");
      out.write("            height: 100vh;\n");
      out.write("            padding: 20px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .login-container {\n");
      out.write("            background: white;\n");
      out.write("            padding: 40px;\n");
      out.write("            border-radius: 12px;\n");
      out.write("            width: 100%;\n");
      out.write("            max-width: 400px;\n");
      out.write("            box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);\n");
      out.write("            animation: slideIn 0.5s ease-out;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @keyframes slideIn {\n");
      out.write("            from {\n");
      out.write("                opacity: 0;\n");
      out.write("                transform: translateY(20px);\n");
      out.write("            }\n");
      out.write("            to {\n");
      out.write("                opacity: 1;\n");
      out.write("                transform: translateY(0);\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @keyframes focusPulse {\n");
      out.write("            0% {\n");
      out.write("                box-shadow: 0 0 0 3px rgba(102, 126, 234, 0.1);\n");
      out.write("            }\n");
      out.write("            50% {\n");
      out.write("                box-shadow: 0 0 0 6px rgba(102, 126, 234, 0.2);\n");
      out.write("            }\n");
      out.write("            100% {\n");
      out.write("                box-shadow: 0 0 0 3px rgba(102, 126, 234, 0.1);\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        h2 {\n");
      out.write("            text-align: center;\n");
      out.write("            color: #1a202c;\n");
      out.write("            margin-bottom: 8px;\n");
      out.write("            font-size: 28px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .subtitle {\n");
      out.write("            text-align: center;\n");
      out.write("            color: #718096;\n");
      out.write("            font-size: 14px;\n");
      out.write("            margin-bottom: 30px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .home-link {\n");
      out.write("            text-align: center;\n");
      out.write("            margin-bottom: 20px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .home-link a {\n");
      out.write("            color: #667eea;\n");
      out.write("            text-decoration: none;\n");
      out.write("            font-size: 14px;\n");
      out.write("            transition: color 0.3s;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .home-link a:hover {\n");
      out.write("            color: #764ba2;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        hr {\n");
      out.write("            border: none;\n");
      out.write("            height: 1px;\n");
      out.write("            background: #e2e8f0;\n");
      out.write("            margin-bottom: 25px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-group {\n");
      out.write("            margin-bottom: 20px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        label {\n");
      out.write("            display: block;\n");
      out.write("            color: #2d3748;\n");
      out.write("            font-weight: 600;\n");
      out.write("            margin-bottom: 8px;\n");
      out.write("            font-size: 14px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        input, select {\n");
      out.write("            width: 100%;\n");
      out.write("            padding: 12px 14px;\n");
      out.write("            border: 2px solid #e2e8f0;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            font-size: 14px;\n");
      out.write("            font-family: inherit;\n");
      out.write("            transition: all 0.3s;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        input:focus, select:focus {\n");
      out.write("            outline: none;\n");
      out.write("            border-color: #667eea;\n");
      out.write("            animation: focusPulse 0.6s ease-out;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        button {\n");
      out.write("            width: 100%;\n");
      out.write("            padding: 12px;\n");
      out.write("            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\n");
      out.write("            border: none;\n");
      out.write("            color: white;\n");
      out.write("            font-size: 16px;\n");
      out.write("            font-weight: 600;\n");
      out.write("            cursor: pointer;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            margin-top: 10px;\n");
      out.write("            transition: all 0.3s;\n");
      out.write("            box-shadow: 0 4px 15px rgba(102, 126, 234, 0.4);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @keyframes buttonBounce {\n");
      out.write("            0%, 100% {\n");
      out.write("                transform: translateY(-2px);\n");
      out.write("            }\n");
      out.write("            50% {\n");
      out.write("                transform: translateY(0);\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        button:hover {\n");
      out.write("            animation: buttonBounce 0.6s ease-out;\n");
      out.write("            box-shadow: 0 6px 20px rgba(102, 126, 234, 0.6);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        button:active {\n");
      out.write("            transform: translateY(0);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .error {\n");
      out.write("            color: #e53e3e;\n");
      out.write("            font-weight: 600;\n");
      out.write("            margin-top: 20px;\n");
      out.write("            padding: 12px;\n");
      out.write("            background: #fff5f5;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            border-left: 4px solid #e53e3e;\n");
      out.write("            font-size: 14px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .back-arrow {\n");
      out.write("            display: inline-block;\n");
      out.write("            width: 20px;\n");
      out.write("            height: 20px;\n");
      out.write("            margin-right: 8px;\n");
      out.write("            animation: slideInLeft 0.4s ease-out;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @keyframes slideInLeft {\n");
      out.write("            from {\n");
      out.write("                opacity: 0;\n");
      out.write("                transform: translateX(-10px);\n");
      out.write("            }\n");
      out.write("            to {\n");
      out.write("                opacity: 1;\n");
      out.write("                transform: translateX(0);\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .back-arrow:hover {\n");
      out.write("            animation: arrowHover 0.3s ease-out forwards;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @keyframes arrowHover {\n");
      out.write("            to {\n");
      out.write("                transform: translateX(-3px);\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<div class=\"login-container\">\n");
      out.write("    <h2>Campus Sync</h2>\n");
      out.write("    <p class=\"subtitle\">College Management System</p>\n");
      out.write("\n");
      out.write("    <div style=\"display: flex; justify-content: center; margin-top: 12px; margin-bottom: 25px;\">\n");
      out.write("        <a href=\"index.jsp\"\n");
      out.write("           style=\"\n");
      out.write("                display: flex;\n");
      out.write("                align-items: center;\n");
      out.write("                gap: 6px;\n");
      out.write("                color: #667eea;\n");
      out.write("                text-decoration: none;\n");
      out.write("                font-size: 15px;\n");
      out.write("                font-weight: 500;\n");
      out.write("                transition: 0.25s ease;\n");
      out.write("           \"\n");
      out.write("           onmouseover=\"this.style.color='#764ba2'; this.children[0].style.transform='translateX(-3px)';\"\n");
      out.write("           onmouseout=\"this.style.color='#667eea'; this.children[0].style.transform='translateX(0)';\">\n");
      out.write("\n");
      out.write("            <svg width=\"16\" height=\"16\" viewBox=\"0 0 24 24\" fill=\"none\"\n");
      out.write("                 stroke=\"currentColor\" stroke-width=\"2\"\n");
      out.write("                 style=\"transition: 0.25s ease;\">\n");
      out.write("                <polyline points=\"15 18 9 12 15 6\"></polyline>\n");
      out.write("            </svg>\n");
      out.write("\n");
      out.write("            Back to Home\n");
      out.write("        </a>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    <form action=\"auth\" method=\"post\">\n");
      out.write("        <div class=\"form-group\">\n");
      out.write("            <label for=\"email\">Email or Username</label>\n");
      out.write("            <input type=\"text\" id=\"email\" name=\"email\" required>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"form-group\">\n");
      out.write("            <label for=\"password\">Password</label>\n");
      out.write("            <input type=\"password\" id=\"password\" name=\"password\" required>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"form-group\">\n");
      out.write("            <label for=\"role\">Select Role</label>\n");
      out.write("            <select id=\"role\" name=\"role\" required>\n");
      out.write("                <option value=\"\">Choose your role...</option>\n");
      out.write("                <option value=\"student\">Student</option>\n");
      out.write("                <option value=\"faculty\">Faculty</option>\n");
      out.write("                <option value=\"admin\">Administrator</option>\n");
      out.write("            </select>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <button type=\"submit\">Sign In</button>\n");
      out.write("    </form>\n");
      out.write("\n");
      out.write("    ");

        if (request.getAttribute("error") != null) {
    
      out.write("\n");
      out.write("        <p class=\"error\">");
      out.print( request.getAttribute("error") );
      out.write("</p>\n");
      out.write("    ");

        }
    
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
