/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.112
 * Generated at: 2025-11-19 05:09:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.servlet.http.HttpSession;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("javax.servlet.http.HttpSession");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    HttpSession s = request.getSession(false);

    if (s == null || !"admin".equals(s.getAttribute("role"))) {
        response.sendRedirect(request.getContextPath() + "/login.jsp");
        return;
    }

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\">\n");
      out.write("    <title>Admin Dashboard - CampusSync</title>\n");
      out.write("    <style>\n");
      out.write("        * {\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("            box-sizing: border-box;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        body {\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n");
      out.write("            background: #f7fafc;\n");
      out.write("            color: #2d3748;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Added modern header with gradient background */\n");
      out.write("        .header {\n");
      out.write("            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\n");
      out.write("            color: white;\n");
      out.write("            padding: 20px 30px;\n");
      out.write("            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: space-between;\n");
      out.write("            align-items: center;\n");
      out.write("            animation: slideDown 0.4s ease-out;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @keyframes slideDown {\n");
      out.write("            from {\n");
      out.write("                opacity: 0;\n");
      out.write("                transform: translateY(-20px);\n");
      out.write("            }\n");
      out.write("            to {\n");
      out.write("                opacity: 1;\n");
      out.write("                transform: translateY(0);\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .header h2 {\n");
      out.write("            font-size: 24px;\n");
      out.write("            font-weight: 700;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .header-user {\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            gap: 20px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .logout-btn {\n");
      out.write("            background: rgba(255, 255, 255, 0.2);\n");
      out.write("            color: white;\n");
      out.write("            text-decoration: none;\n");
      out.write("            padding: 8px 16px;\n");
      out.write("            border-radius: 6px;\n");
      out.write("            font-size: 14px;\n");
      out.write("            font-weight: 600;\n");
      out.write("            transition: all 0.3s;\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.3);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .logout-btn:hover {\n");
      out.write("            background: rgba(255, 255, 255, 0.3);\n");
      out.write("            animation: buttonPulse 0.4s ease-out;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @keyframes buttonPulse {\n");
      out.write("            0%, 100% {\n");
      out.write("                transform: scale(1);\n");
      out.write("            }\n");
      out.write("            50% {\n");
      out.write("                transform: scale(1.05);\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .container {\n");
      out.write("            padding: 40px 30px;\n");
      out.write("            max-width: 1200px;\n");
      out.write("            margin: 0 auto;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Added modern card-based layout for options */\n");
      out.write("        .options-grid {\n");
      out.write("            display: grid;\n");
      out.write("            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));\n");
      out.write("            gap: 20px;\n");
      out.write("            margin-top: 30px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .option-card {\n");
      out.write("            background: white;\n");
      out.write("            padding: 25px;\n");
      out.write("            border-radius: 10px;\n");
      out.write("            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);\n");
      out.write("            transition: all 0.3s cubic-bezier(0.34, 1.56, 0.64, 1);\n");
      out.write("            border: 1px solid #e2e8f0;\n");
      out.write("            cursor: pointer;\n");
      out.write("            animation: cardFadeIn 0.5s ease-out forwards;\n");
      out.write("            opacity: 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @keyframes cardFadeIn {\n");
      out.write("            from {\n");
      out.write("                opacity: 0;\n");
      out.write("                transform: translateY(20px);\n");
      out.write("            }\n");
      out.write("            to {\n");
      out.write("                opacity: 1;\n");
      out.write("                transform: translateY(0);\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .options-grid .option-card:nth-child(1) { animation-delay: 0.1s; }\n");
      out.write("        .options-grid .option-card:nth-child(2) { animation-delay: 0.2s; }\n");
      out.write("        .options-grid .option-card:nth-child(3) { animation-delay: 0.3s; }\n");
      out.write("\n");
      out.write("        .option-card:hover {\n");
      out.write("            transform: translateY(-8px) scale(1.02);\n");
      out.write("            box-shadow: 0 12px 28px rgba(102, 126, 234, 0.25);\n");
      out.write("            border-color: #667eea;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .icon {\n");
      out.write("            font-size: 40px;\n");
      out.write("            margin-bottom: 10px;\n");
      out.write("            color: #333;\n");
      out.write("            display: inline-block;\n");
      out.write("            transition: transform 0.3s cubic-bezier(0.34, 1.56, 0.64, 1);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .option-card:hover .icon {\n");
      out.write("            transform: scale(1.3) rotate(5deg);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .option-card a {\n");
      out.write("            display: block;\n");
      out.write("            color: #667eea;\n");
      out.write("            text-decoration: none;\n");
      out.write("            font-weight: 600;\n");
      out.write("            font-size: 18px;\n");
      out.write("            transition: color 0.3s;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .option-card a:hover {\n");
      out.write("            color: #764ba2;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .option-card p {\n");
      out.write("            color: #718096;\n");
      out.write("            font-size: 14px;\n");
      out.write("            margin-top: 10px;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<div class=\"header\">\n");
      out.write("    <h2>Admin Dashboard</h2>\n");
      out.write("    <div class=\"header-user\">\n");
      out.write("        <span>Welcome, ");
      out.print( s.getAttribute("name") );
      out.write("</span>\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/auth?action=logout\" class=\"logout-btn\">Logout</a>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"container\">\n");
      out.write("    <h3 style=\"color: #2d3748; font-size: 20px; margin-bottom: 10px;\">Admin Options</h3>\n");
      out.write("    <p style=\"color: #718096; margin-bottom: 30px;\">Manage students, faculty, and system notices</p>\n");
      out.write("\n");
      out.write("    <div class=\"options-grid\">\n");
      out.write("\n");
      out.write("        <!-- Manage Students -->\n");
      out.write("        <div class=\"option-card\">\n");
      out.write("            <div class=\"icon\"><i class=\"fas fa-user-graduate\"></i></div>\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/adminPanel?action=students\">Manage Students</a>\n");
      out.write("            <p>Add, view, and manage student records and enrollment</p>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"option-card\">\n");
      out.write("            <div class=\"icon\"><i class=\"fas fa-clipboard-list\"></i></div>\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/adminPanel?action=notices\">View Notices</a>\n");
      out.write("            <p>View Latest Updates and Notices</p>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Manage Faculty -->\n");
      out.write("        <div class=\"option-card\">\n");
      out.write("            <div class=\"icon\"><i class=\"fas fa-chalkboard-teacher\"></i></div>\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/adminPanel?action=faculty\">Manage Faculty</a>\n");
      out.write("            <p>Add, view, and manage faculty member information</p>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Manage Courses -->\n");
      out.write("        <div class=\"option-card\">\n");
      out.write("            <div class=\"icon\"><i class=\"fas fa-book\"></i></div>\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/adminPanel?action=courses\">Manage Courses</a>\n");
      out.write("            <p>Add, update and organize all academic courses offered</p>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Manage Subjects -->\n");
      out.write("        <div class=\"option-card\">\n");
      out.write("            <div class=\"icon\"><i class=\"fas fa-book-open\"></i></div>\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/adminPanel?action=subjects\">Manage Subjects</a>\n");
      out.write("            <p>Define course subjects, assign faculty and update subjects</p>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Publish Notice -->\n");
      out.write("        <div class=\"option-card\">\n");
      out.write("            <div class=\"icon\"><i class=\"fas fa-bullhorn\"></i></div>\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/adminPanel?action=addNotice\">Publish Notice</a>\n");
      out.write("            <p>Create and broadcast important announcements</p>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
